### ISSUE TITLE
No RBAC permission to create events

### ISSUE THREAD

**Issue by Learloj** [nolar/kopf#1016]
### Keywords

documentation rbac events

### Problem

I followed the documentation around RBAC to create a Role and ClusterRole for an Operator I have been working on. Upon deployment, the Operator logged an error related to not having permissions to create events in the namespace where it was reconciling a CRD in.

The documentation mention events permissions as part of the Role, which is namespaced: https://github.com/nolar/kopf/blob/main/docs/deployment-rbac.yaml#L49-L52

Should the permissions for events not be moved to the ClusterRole, allowing the operator to publish events in all namespaces, not just its own? If yes, then I am more than happy to make a PR for this.

**Comment by asteven** [comment]
This works for me:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: some-cluster-role
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
    
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch] 
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
    
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
    
  # Application
  # add app specific rules here
  ```
