### ISSUE TITLE
kopf.timer / kopf.daemon disable kopf.on* handlers

### ISSUE THREAD

**Issue by sc0rp10** [nolar/kopf#1122]
### Keywords

timer, daeemon, handler

### Problem

Hello, I try to build an own operator that creates few simple resources by some CRD, those need to be updated by some external data. I check for that data periodically, using timer/daemon.

My handlers.py is deadly simple - I just copied example from kopf website: 
```python
import kopf
import logging

@kopf.on.create('ephemeralvolumeclaims')
def create_fn(body, **kwargs):
    logging.info(f"A handler is called with body: {body}")

@kopf.timer('ephemeralvolumeclaims', interval=1.0)
def ping_kex(spec, **kwargs):
    logging.info(f"A timer is called")


```
<details>
<summary>CRD</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ephemeralvolumeclaims.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: EphemeralVolumeClaim
    plural: ephemeralvolumeclaims
    singular: ephemeralvolumeclaim
    shortNames:
      - evcs
      - evc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

```
</details>

<details>
<summary>Object</summary>

```yaml
apiVersion: kopf.dev/v1
kind: EphemeralVolumeClaim
metadata:
  name: my-claim


```
</details>

When I run this file without timer or daemon, everything works like a charm, but once I add timer/daemon, my on* handlers stopped working without any information.

What can be wrong with this configuration? What is the best approach to have some periodic watch for some external system to provide my k8s resources with some information from that system?

UPD: I use macOS and run kopf directly from macos as `kopf run ...`
