### ISSUE TITLE
Automatic CRD Manifest Generation

### ISSUE THREAD

**Issue by tinyzimmer** [nolar/kopf#524]
## Problem

I personally use `operator-sdk` and `kubebuilder` a lot and one of the things I love about them is the ability to generate CustomResourceDefinition manifests from the type declarations in my gocode. 

Wouldn't it be awesome if kopf could do this?! In addition to the doc/crd generation potential, kopf handlers in the future could inject populated classes when handlers run. Adding a sort of "object safety" to the mix.

**Are there existing features close to solving this problem? Why don't they work?**

Not that I'm aware of.

## Proposal

For starters, I'm toying with what a similar CRD generation could look like in python. The idea being, along with their decorated functions, the user can provide a decorated class. An additional command such as `kopf generate k8s` or something can then pull in these decorated classes and use them to generate a CRD.

I have proof-of-concept code that provides the functionality outlined below. I'm happy to open a PR to try to stitch it into `kopf`. 

```python
@kopf.CRD(group="kopf.io", status_subresource=True)  # I have several additional options already such as defining 'scope', 'version', etc.
class RedisCluster(object):

    def spec(self):
        """
        @config -- Configuration options for redis.
        @someString -- This is an example string.
        @someBool -- This is an example bool object.
        @someInt -- This is an example integer object.
        @someList -- This is an example array object.
        """
        return {
            'config': RedisConfig,
            'someString': str,
            'someBool': bool,
            'someInt': int,
            'someList': [str]
        }

class RedisConfig(object):

    def attrs(self):
        """
        @someString -- This is an example string inside the redis config.
        """
        return {
            'someString': str
        }

print(RedisCluster.generate_k8s())  # Generates the CRD yaml
```

The decoration on the primary `RedisCluster` object (at least with what I have so far) adds an additional `generate_k8s()` method to the class, which is what the `kopf generate k8s` or whatever could call. The example above produces this:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisclusters.kopf.io
spec:
  group: kopf.io
  names:
    kind: RedisCluster
    listKind: RedisClusterList
    plural: redisclusters
    singular: rediscluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RedisCluster is the Schema for the redisclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RedisClusterSpec defines the desired state of RedisCluster
            properties:
              config:
                description: Configuration options for redis.
                properties:
                  someString:
                    description: This is an example string inside the redis config.
                    type: string
                type: object
              someBool:
                description: This is an example bool object.
                type: boolean
              someInt:
                description: This is an example integer object.
                type: integer
              someList:
                description: This is an example array object.
                items:
                  type: string
                type: array
              someString:
                description: This is an example string.
                type: string
    served: true
    storage: true
    subresources:
      status: {}
```

Full support could include the ability to do `anyOf` and `enums`. Was a little too involved for the quick POC I put together. 

So...whadya think?

## Checklist

- [X] Many users can benefit from this feature, it is not a one-time case
- [X] The proposal is related to the K8s operator framework, not to the K8s client libraries
