### ISSUE TITLE
Kopf adding removing finalizerr on some custom resources

### ISSUE THREAD

**Issue by jamiechapmanbrn** [nolar/kopf#587]
We recently upgraded from kopf 0.25 to 0.28. For whatever reason it's modifying some custom resources constantly, adding and removing the finalizer. This is hitting our customresource cockroachdb, seemingly exclusively.

When this happens it's sending an update through to eventhandler 

cockroachdb's spec looks like this:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cockroachdbs.agilicus.com
spec:
  scope: Namespaced
  group: agilicus.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: cockroachdb
    plural: cockroachdbs
    singular: cockroachdb
  additionalPrinterColumns:
    - name: DBName
      type: string
      priority: 0
      JSONPath: .spec.dbname
      description: The name of the cockroachdb database
    - name: User
      type: string
      priority: 0
      JSONPath: .spec.user
      description: The initial user of the cockroachdb database
    - name: Restore
      type: boolean
      priority: 0
      JSONPath: .spec.restore
      description: Enable Restore from database
    - name: RestoreFrom
      type: string
      priority: 0
      JSONPath: .spec.restorefrom
      description: Restore database from backup based on date/time (dateparser)
```

The watcher looks like this:
```
        @kopf.on.event(
            "agilicus.com",
            "v1",
            "cockroachdbs",
            registry=self.registry,
        )
        def event(logger, event, body, status, **_):
            self.send_event(
                .
                .
                .
            )
```

* Kopf version: 0.28
* Kubernetes version: v1.18.9
* Python version: 3.8
* OS/platform: ubuntu
