### ISSUE TITLE
I want to capture deployment update information. Can it be done?

### ISSUE THREAD

**Issue by bibi520** [nolar/kopf#653]

**Comment by nolar** [comment]
Can you please clarify the question? I didn’t get it, sorry. Maybe an example?

**Comment by bibi520** [comment]
I want to capture the update status of deployment through kopf and notify webhook of deployment running status

**Comment by amilenovic** [comment]
I also wanted to listen on deployment resource change, ```status.availabile``` field .

I tried with ```preserveUnknownFields: true``` as suggested, but did not work. Any suggestion?

**Comment by nolar** [comment]
Yes, this should be possible in theory (if such field really exists in deployments — I cannot check at the moment). I see no reason why not. 

However, preserveUnknownFields is a part of **custom** resource definitions. You cannot redefine the builtin resources. Can you please clarify where did you put that field?

**Comment by amilenovic** [comment]
Ok, thanks for answer for preserveUnknownFields.

Here is the example of deployment I was referring:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-deployment
  labels:
    app: flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow
  template:
    metadata:
      labels:
        app: flow
    spec:
      containers:
      - name: flow-container
        image: alpine
        command: ['sh', '-c', 'echo "Hello, {{flow}}!" && sleep 60']
```

As you can see, after 60 sec the ```available``` field will change from 1 to 0 and after starting container again, from 0 to 1. I'd like to capture such events.

```
# kubectl get deployments -w
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
flow-deployment   1/1     1            1           2s
flow-deployment   0/1     1            0           61s
flow-deployment   1/1     1            1           62s
```

Here is the code, that is not being triggered at the moment:

```
@kopf.on.update('deployment')
def flow_deployment_updated(name, **kwargs):
    print(f"changed: {name}")
```

Any suggestion?

Thanks in advance,
Aleksandar
