### ISSUE TITLE
kopf peering with shared volume 

### ISSUE THREAD

**Issue by sajuptpm** [nolar/kopf#663]
#### Steps
- I am using kopf 1.29.1:
- created crds required for peering : https://github.com/nolar/kopf/blob/c92258b7ad2b172129754ae816e9d550e8bcb854/peering.yaml
- changed "replica=2" in deployment kind
- i have mounted a volume to operator container
- I am getting "**Multi-Attach error for volume**" error when applying the deployment.

**I want to share some data among the operator pods. What are the best ways** ?

**I dont have shared volume like NFS , ReadWriteMany doesn't work.**

--------------------------------------------

#### kopf settings

```
@kopf.on.startup()
def configure(settings: kopf.OperatorSettings, **_):
    #settings.peering.standalone = True
    settings.peering.priority = random.randint(0, 32767)
    settings.peering.stealth = True
    settings.persistence.finalizer = "ehl.ees/kopf-finalizer"
    settings.watching.connect_timeout = 1 * 60
    settings.watching.server_timeout = 1 * 300
    settings.watching.client_timeout = 1 * 600
```

--------------------------------------------
#### docker command
```
CMD kopf run --liveness=http://0.0.0.0:$PORT/healthz main.py --verbose
```
--------------------------------------------

#### Voume which i am using
```
kind: PersistentVolumeClaim
metadata:
spec:
  accessModes:
  **- ReadWriteOnce**
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-xxxxxxxxxxxxxxxxx
status:
  accessModes:
  - **ReadWriteOnce**
  capacity:
    storage: 3Gi
  phase: Bound
```
--------------------------------------------
