### ISSUE TITLE
Persist temporary/permanent errors

### ISSUE THREAD

**Issue by nolar** [nolar/kopf#692]
## Problem

Currently, all temporary or permanent errors are lost in logs (nobody reads logs). Also, they are sent as K8s Events, but those are garbage-collected fast. The errors are not persisted in resources themselves.

The temporary errors are stored in Kopf's progress storage, but it only works as long as the status storage is enabled. If it is only an annotations storage (which has to be made a default soon: https://github.com/nolar/kopf/issues/685#issuecomment-780212085), then those errors will not be seen too.

Original thread: https://twitter.com/GrahamDumpleton/status/1362235230946357248

## Proposal

It would be good to have the error information stored directly on the resource the same as it is done for the handler's results, so that no extra lines with `patch.status['some-error'] = "..."` would be needed, and they all would be separated by handler ids (fn names or id= params) automatically.

A sample code:

```python
import kopf

@kopf.on.create('kex')
def fn1(**_):
    raise kopf.PermanentError("Credentials for Foo API are not valid. Fix it plz!")

@kopf.on.create('kex')
def fn2(**_):
    raise kopf.TermporaryError("Not ready yet... Just wait.", delay=10)

@kopf.on.create('kex')
def fn3(**_):
    raise OSError("Oops...")

@kopf.on.create('kex')
def fn4(**_):
    return "I'm okay"
```

Then, the errors are persisted:

```yaml
apiVersion: kopf.dev/v1
kind: KopfExample
spec: ...
status:
  fn1-error:
    type: PermanentError
    message: Credentials for Foo API are not valid. Fix it plz!
  fn2-error:
    type: TemporaryError
    message: Not ready yet... Just wait.
  fn3-error:
    type: OSError
    message: Oops...
  fn4: I'm okay
```

This later can be used in the printed columns:

```
$ kubectl get kex
NAME FIELD STATUS1
kex1 value Credentials for Foo API are not valid. Fix it plz!
```

DSL & behaviour challenges:

* How do we make it optional? Builtin resources (pods, etc) cannot store arbitrary status data. (The results can be optional by just not returning anything.)
* What's the status structure? Key names? Do we mix errors with results? Or separate them?
* Do we store builtin/Kopf's error class names (not the messages)? Or only the 3rd-party ones?
* Should a temporary error be removed after the handler succeeds?
* Can multiple errors point to the same field, e.g. `.status.message` instead of per-handler `.status.{id}-error.message` (to have only one printed column for everything)?

And also:

* Is the complexity of the generalised solution lower than just adding a single `patch.status['fn1-error'] = {...}` message before `raise...`? (It should be as simple as storing those function results now.)
