### ISSUE TITLE
Unexpected behavior of update/create handlers with status field

### ISSUE THREAD

**Issue by leoruiz** [nolar/kopf#706]
## Long story short

I am trying to perform some action once a Job is completed. I was expecting handling on update to status.succeeded to do the trick. 

The handler never performs the action. I realize I may want to use new= instead of value= but neither worked.

```python
import kopf

# Not handled
@kopf.on.update(
    "batch",
    "v1",
    "jobs",
    labels={"app.kubernetes.io/name": "my-job"},
    field="status.succeeded",
    value=1,
)
def my_job_complete_fn(namespace: str, status: Any, **_: Any) -> None:
...
```

If I use on.create instead of on.update it works

```python
import kopf

# Handled
@kopf.on.create(
    "batch",
    "v1",
    "jobs",
    labels={"app.kubernetes.io/name": "my-job"},
    field="status.succeeded",
    value=1,
)
def my_job_complete_fn(namespace: str, status: Any, **_: Any) -> None:
...
```

When I create the job, I can see it using kubectl go from:

```
  status:
    active: 1
    startTime: "2021-03-04T17:43:45Z"
```

to

```
  status:
    completionTime: "2021-03-04T17:43:49Z"
    conditions:
    - lastProbeTime: "2021-03-04T17:43:49Z"
      lastTransitionTime: "2021-03-04T17:43:49Z"
      status: "True"
      type: Complete
    startTime: "2021-03-04T17:43:45Z"
    succeeded: 1
```

I may be misunderstanding but this seems unexpected to me that on.create works since when the job is created it does not have the status.succeeded field. And on.update with status.succeded does not.
I tried reading the documentation but I was not able to clear my confusion.

## Description

<details><summary>The code snippet to reproduce the issue</summary>

</details>

<details><summary>The exact command to reproduce the issue</summary>

```bash
kopf run --standalone --all-namespaces -m myoperator
```
</details>

## Environment

* Kopf version: 1.29.2
* Kubernetes version: 1.18.14
* Python version: 3.9
* OS/platform: Debian
