### ISSUE TITLE
Example deployment configs for webhooks

### ISSUE THREAD

**Issue by sambhav** [nolar/kopf#785]
## Question

Currently there are is very little documentation on how to deploy an admission controller written in kopf.
It would be nice to update https://kopf.readthedocs.io/en/stable/deployment/ with this information.

Currently I am struggling to figure out which pieces I need to set for an admission controller to be properly deployed as a K8s native app.

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

webhook, admission controller, deployment

**Comment by sambhav** [comment]
@nolar I would be happy to help add this to the docs, but I don't quite understand which parts kopf handles when deployed as a k8s native app. 

- Does it automatically generate the certs and update the webhook config?
- Does it need a service to be created?
- What config/settings should my webhook itself use? I wasn't sure which of the webhook servers were appropriate in this case.

**Comment by nolar** [comment]
> I would be happy to help add this to the docs, …

I would be happy to review and comment on that! Though, I have a feeling that it will be a huge lengthy text worth a blog post or a series of posts or maybe a small book.

More on that, some "convenient" practices can be opinionated and considered less secure than needed. In this regard, I am not sure Kopf's documentation is a good place to give any recommendations on the security-related topics (this is out of the scope of the framework).

But at least I would be happy to add a link (or a few links) to such manuals or guides.

> … which parts kopf handles when deployed as a k8s native app.

Can you please clarify the question?

Essentially, you need to expose a port where Kopf listens from the pod, then create a service pointing to that pod, and then create (manually) `[Validating|Mutating]WebhookConfiguration` objects pointing to that service. I thought of Kopf generating them (codenamed "Kopf SDK"), but didn't prioritise this feature yet.

Besides, generate SSL certificates either way (e.g. via cert-manager, openssl, or some other CA — depending on the company policies). Put the CA to `caBundle`. Put the SSL cert+private key to the operator (I guess, as Secrets mounted as a volume).

Create an on-startup handler that sets the webhook server with all these certs & ports — as per the existing documentation.

Optionally, add some health checks (liveness/readiness probes).

In some environments and companies, cluster-local Ingress objects can be used for HTTPS endpoints instead of self-served HTTPS servers in the pod (in that case, the pod's server will be simple HTTP).

In some other extremely secure environments, client-side authentication must be added — (client=K8s, server=webhook), so that the webhook server would know that it is called by proper K8s and not by something else — which can only be done in the cluster configs, i.e. requires admin privileges, not doable from the user side. This is optional, luckily.

I guess, something like this.

The same scenario applies to any webhook server, not necessary Kopf-based. This is why I think it can be a good blog post — with Kopf used only as an example. Technically, you can make webhook servers even with Flask or aiohttp or (maybe) Django or whatever serving HTTP.

> Does it automatically generate the certs and update the webhook config?

Kopf does automatically generate self-signed SSL certs (which are also CAs for themselves) — but that is supposed to be used in the dev mode only. Self-signed SSL certs/CAs are not secure enough for production (regardless of the framework). Kopf supports arbitrary CA/SSL too — when provided via settings.

Kopf also manages the `*WebhookConfiguration` objects at runtime — but I'm not sure this is a good idea for production (there are some caveats). Though, it is less critical than proper proper SSL.

> Does it need a service to be created?

If the webhook server runs inside of K8s, then a service is needed.

If outside, then any URL can work. Magic URLs of K8s pointing to `....service.cluster.local` can also work.

As a starting point, see: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

> What config/settings should my webhook itself use? I wasn't sure which of the webhook servers were appropriate in this case.

Sorry, I didn't get this question.

**Comment by sambhav** [comment]
At the end - this is what I created for a minimal webhook config.

```python
import os
from typing import Any, AsyncIterator, Dict

import kopf


class ServiceTunnel:
    async def __call__(
        self, fn: kopf.WebhookFn
    ) -> AsyncIterator[kopf.WebhookClientConfig]:
        namespace = os.environ.get("NAMESPACE")
        name = os.environ.get("SERVICE_NAME")
        service_port = int(os.environ.get("SERVICE_PORT", 443))
        container_port = int(os.environ.get("CONTAINER_PORT", 9443))
        server = kopf.WebhookServer(port=container_port, host=f"{name}.{namespace}.svc")
        async for client_config in server(fn):
            client_config["url"] = None
            client_config["service"] = kopf.WebhookClientConfigService(
                name=name, namespace=namespace, port=service_port
            )
            yield client_config


@kopf.on.startup()
def configure(settings: kopf.OperatorSettings, **_):
    settings.admission.server = ServiceTunnel()
    settings.admission.managed = os.environ.get("WEBHOOK_NAME")
```

and the corresponding deployment config is - 

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kopf
  name: defaulter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: defaulter-role-cluster
rules:
  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io, admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  # You can put in the resources you want to default
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, watch, patch, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: defaulter-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: defaulter-role-cluster
subjects:
  - kind: ServiceAccount
    name: defaulter
    namespace: kopf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaulter-webhook
  namespace: kopf
  labels:
    application: defaulter-webhook
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: defaulter-webhook
  template:
    metadata:
      labels:
        application: defaulter-webhook
    spec:
      serviceAccountName: defaulter
      containers:
      - name: controller
        image: webhook
        imagePullPolicy: Always
        ports:
        - name: https-webhook
          containerPort: 9443
        env:
        - name: NAMESPACE
          value: kopf
        - name: SERVICE_NAME
          value: defaulter-webhook
        - name: SERVICE_PORT
          value: "443"
        - name: CONTAINER_PORT
          value: "9443"
        - name: WEBHOOK_NAME
          value: "defaults.kopf.io"
---
apiVersion: v1
kind: Service
metadata:
  name: defaulter-webhook
  namespace: kopf
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    application: defaulter-webhook
```

One other bug I discovered is that currently kopf uses the python function name to create the paths for webhook which contains underscores which is not a valid path value for service paths

```python
'message': 'Invalid value: "/defaults_items": segment[0]: a DNS-1123 subdomain must consist of lower case alphanumeric characters, \'-\' or \'.\', and must start and end with an alphanumeric character (e.g. \'example.com\', regex used for validation is \'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\')',
```
