### ISSUE TITLE
Trying to configure custom annotations fail

### ISSUE THREAD

**Issue by xavierbaude** [nolar/kopf#817]
### Long story short

I'm running several Kopf operator since a while with the release 0.28. To avoid the issue https://github.com/nolar/kopf/issues/372 I configured an annotation for the diffbase_storage tuning. Now I'm trying to switch to the last 1.33 release and follow the documentation https://kopf.readthedocs.io/en/stable/configuration/#change-detection with no luck.

Settings
```python
    settings.persistence.diffbase_storage = kopf.AnnotationsDiffBaseStorage(
        name='networkpolicy.last-handled-configuration',
    )
```

Says 
```
TypeError: __init__() got an unexpected keyword argument 'name'
```
and trying
```python
    settings.persistence.diffbase_storage = kopf.AnnotationsDiffBaseStorage(
        prefix='kopf.zalando.org',
        key='networkpolicy.last-handled-configuration'
    )
```

give me  

```yaml
metadata:
  annotations:
    kopf.zalando.org/networkpolicy.last-handled-confi-n7DPQQ: |
      {"spec":{"finalizers":["kubernetes"]}}
    kopf.zalando.org/networkpolicy.last-handled-configuration: |
      {"spec":{"finalizers":["kubernetes"]}}
```

### Kopf version

V1.33
### Kubernetes version

1.19

### Python version

3.8
