### ISSUE TITLE
Disable "Results delivery"

### ISSUE THREAD

**Issue by jeff-minard-ck** [nolar/kopf#848]
### Problem

The documentation covers "Results delivery" in that the data structure returned from your handler function will be patched onto the status of the object being operated upon.

I've got a setup in which I've given the operator permission to scale deployments, but NOT patch the main deployment object. It's a pretty rare kind of setup that is rather specific to deployments. It's setup this way because I want to have "least privilege" and the operator is designed for scaling the deployment, so it need not edit it. The RBAC looks kinda like this:

```yaml
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
```

However, when run this results in the operator complaining about not being able to patch the deployment itself, I assume with the handler results.

```
kopf.clients.errors.APIClientResponseError: 403, message='deployments.apps \"snakey2\" is forbidden: User \"system:serviceaccount:scaler:scaler\" cannot patch resource \"deployments\" in API group \"apps\" in the namespace \"scaler\"', url=URL('https://10.247.224.1:443/apis/apps/v1/namespaces/scaler/deployments/snakey2')
```

Is there a way to disable the "results delivery"? Perhaps an option to the `@kopf.on.daemon` type decorator(s), a global option, or best yet I suspect, a specific return type, something like:

```python
@kopf.on.daemon('apps', 'v1', 'deployments')
def scaler(**_):
	return kopf.NO_RESULTS_DELIVERY
```

Thanks!
