### ISSUE TITLE
Embedded kopf doesn't detect resource creation

### ISSUE THREAD

**Issue by draghuram** [nolar/kopf#888]
### Keywords

embed

### Problem

Here is the "testevents" CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testevents.example.com
spec:
  scope: Namespaced
  group: example.com
  names:
    kind: TestEvent
    plural: testevents
    singular: testevent
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
```
Here is the operator that is run with ``kopf run`` and it works. When I create the resource, I can see that kopf recognizes the creation.

```
import kopf

@kopf.on.create('testevents')
def create_fn(body, **kwargs):
    print(f"A handler is called with body: {body}")
```
But when I try to embed kopf as follows, it doesn't reconcile the resource creation (I created another resource):
```
import asyncio
import kopf
import threading

from kubernetes import config as k8sconfig

def kopf_thread():
    asyncio.run(kopf.operator())

k8sconfig.load_kube_config()

thread = threading.Thread(target=kopf_thread)
thread.start()
```
Any help is greatly appreciated.
