### ISSUE TITLE
How to handle diff of new dict vs. existing dict?

### ISSUE THREAD

**Issue by boostasbjorn** [nolar/kopf#892]
### Keywords

diff field new old existing dict

### Problem

If I start with the following object:
```
apiVersion: example.com/v1
kind: Website
metadata:
  name: sample-site
spec:
  config:
    url: http://example.com/
```

Then I add a previously missing dict:
```
apiVersion: example.com/v1
kind: Website
metadata:
  name: sample-site
spec:
  static:
    url: http://example.com/
  logging:
    level: INFO
```

Then `diff=(('add', ('spec', 'logging'), None, {'level': 'INFO'}),)`.

-----------------------------------------------------------------------------------------------------

However, if I start with the `logging` dict already defined:
```
apiVersion: example.com/v1
kind: Website
metadata:
  name: sample-site
spec:
  config:
    url: http://example.com/
  logging:
    upload: false
```

Then I add the same info as last time:
```
apiVersion: example.com/v1
kind: Website
metadata:
  name: sample-site
spec:
  config:
    url: http://example.com/
  logging:
    level: INFO
    upload: false
```

Then `diff=(('add', ('spec', 'logging', 'level'), None, 'INFO'),)`.

-----------------------------------------------------------------------------------------------------

So I would just like to ask for tips on how to handle that. I'd like to react to when `spec.logging.level` is added, but I find it awkward to have to check "turtles all the way down" so to say :smile: Got any tips?
