### ISSUE TITLE
Ignore changes to specific label/annotation.

### ISSUE THREAD

**Issue by cannibalisticcow** [nolar/kopf#989]
Is there a way to ignore changes to specified annotations or labels?

## Description

I have a CR which when an update or change is made to the object it triggers a reconcile, when this happens one or multiple annotations are updated with information such as the last time stamp of when a reconcile succeeded and potentially how many times that object has been changed. The problem with this is that it can cause a loop where on.update is used as when that annotation is updated it triggers a new update where the field is then updated again.

### What I was hoping for
```
@kopf.on.update('kopfexamples',
                annotations={'infrastructure/last-reconcile-timestamp': kopf.IGNORE_CHANGES})
def my_handler(spec, **_):
    pass
```
```
apiVersion: infrastructure/v1
kind: myCR
metadata:
  annotations:
    infrastructure/force-renew: "False"
    infrastructure/last-reconcile-timestamp: "2022-12-19T16:56:14Z"
  name: name
spec:
 some-spec
```
