### ISSUE TITLE
How to persist a permanent error in the resource status?

### ISSUE THREAD

**Issue by mledoze** [nolar/kopf#993]
### Keywords

permanent error persistence status

### Problem

Hi, 

when a temporary error is raised, the error is persisted in the resource status:

```yaml
status:
  kopf:
    delayed: 2023-01-04T15:03:44.665789
    failure: false
    message: <my error message>
    purpose: create
    retries: 1
    started: 2023-01-04T14:56:43.571987
    success: false
```

However when a permanent error is raised or when the number of retries of a temporary error exceeds a limit, the error is not persisted in the resource status.

Is there a way to persist a permanent error in the resource?

Thank you
